all:
  children:
    webservers:
      hosts:
        web1:
          ansible_host: localhost
          ansible_connection: local
        web2:
          ansible_host: localhost
          ansible_connection: local
      vars:
        http_port: 80
        https_port: 443
        web_root: "/var/www/html"
    dbservers:
      hosts:
        db1:
          ansible_host: localhost
          ansible_connection: local
      vars:
        mysql_port: 3306
        mysql_data_dir: "/var/lib/mysql"
